version: '2'
services:
  rhd_perf_testing:
    build: .
    volumes:
    - .:/home/performance/rhd-performance-tests
    working_dir: /home/performance/rhd-performance-tests
    environment:
    - RHD_PERF_TEST_URL
    - RHD_DRUPAL_USER
    - RHD_DRUPAL_PASSWORD
    - DRUPAL_USER_NUMBER_FROM
    - DRUPAL_USER_NUMBER_TO
    - UNAUTHENTICATED_USER_NUMBER_FROM
    - UNAUTHENTICATED_USER_NUMBER_TO
    - DURATION

