version: '2'
services:
  rhd_perf_testing:
    build: .
    volumes:
    - .:/home/performance/rhd-performance-tests
    working_dir: /home/performance/rhd-performance-tests
    environment:
    - RHD_PERF_TEST_URL
    - DURATION
    - RAMP_UP_TIME
    - RHD_DRUPAL_USER
    - RHD_DRUPAL_PASSWORD


